arc_trustpay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

APP_NAME = settings.APP_NAME

urlpatterns = [
    path('', include('trustpay_landing.urls', namespace='landing')),
    path('', include('trustpay_auth.urls', namespace='auth')),
    path(f"{APP_NAME}-admin/", admin.site.urls),
    path('auth/', include('trustpay_user.urls', namespace='user')),
    path('auth/', include('trustpay_trx.urls', namespace='trx')),
    path('auth/', include('trustpay_admin.urls', namespace='adm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = f"{APP_NAME}"
admin.site.site_title = f"{APP_NAME}"
admin.site.index_title = f"Welcome to {APP_NAME}"

trustpay_trx/urls.py
# My Django imports
from django.urls import path, include

app_name = 'trx'

# My App imports
from trustpay_trx.views import *

# URL patterns for the trustpay_users app
urlpatterns = [
    path('crypto_deposit', CryptoDepositView.as_view(), name="crypto_deposit"),
    path('complete_crypto_deposit', CompleteCryptoDepositView.as_view(), name="complete_crypto_deposit"),

    path('cheque_deposit', ChequeDepositView.as_view(), name="cheque_deposit"),

    path('internal_transfer', InternalTransferView.as_view(), name="internal_transfer"),
    path('validate_recipient_account/', validate_recipient_account, name="validate_recipient_account"),
    path('confirm_internal_transfer', ConfirmInternalTransferView.as_view(), name="confirm_internal_transfer"),

    path('ach_transfer', ACHTransferView.as_view(), name="ach_transfer"),
    path('confirm_ach_transfer', ConfirmACHTransferView.as_view(), name="confirm_ach_transfer"),

    path('d_wire_transfer', DomesticWireView.as_view(), name="d_wire_transfer"),
    path('confirm_d_wire_transfer', ConfirmDomesticWireView.as_view(), name="confirm_d_wire_transfer"),

    path('f_wire_transfer', InternationalWireView.as_view(), name="f_wire_transfer"),
    path('confirm_f_wire_transfer', ConfirmInternationalWireView.as_view(), name="confirm_f_wire_transfer"),

    path('credit_debit_transaction', CreditDebitTransactionView.as_view(), name="credit_debit_transaction"),

    path('take_loan', TakeLoanView.as_view(), name="take_loan"),
    path('repay_loan', RepayLoanView.as_view(), name="repay_loan"),

    path('transactions', TransactionPageView.as_view(), name="transactions"),
]

templates/backend/crypto/complete_deposit.html
{% extends "base_main.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
  {% include "partials/backend/head.html" %}
{% endblock head %}
{% block title %} Complete Crypto Deposit {% endblock %}
{% block content %}
    {% url 'trx:crypto_deposit' as crypto_deposit_url %}
    {% with title_sub="Crypto Deposit" title="Complete Crypto Deposit" url=crypto_deposit_url%}
    {% include "partials/backend/pagetitle.html" %}
    {% endwith %}

<!--begin::App-->
            {% include "partials/backend/messages.html" %}
            <div class="row">
                <div class="col-12 col-xl-6">
                    <div class="card card-h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">Complete Crypto Deposit</h5>
                        </div>

                        <div class="card-body">
                            <p class="text-muted mb-4">You are to make payment of ${{deposit_amount}} using your selected payment method.
                                Screenshot and upload the proof of {{ wallet_address}} payment.</p>
                            <form method ="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="input-group mb-2">
                                    <input type="text" class="form-control" id="walletAddress" name="address" value="{{ wallet_address.crypto_address }}" readonly disabled aria-label="Address" aria-describedby="walletAddress" >
                                    <span class="input-group-text" id="copyAddress" style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#defaultModal"><i class="ri-file-copy-line"></i>
                                    </span>
                                </div>
                                <input type="hidden" name="wallet" value="{{wallet_address.pk}}">
                                <input type="hidden" name="deposit_amount" value="{{deposit_amount}}">
                                {{form|crispy}}
                                <div class="row">
                                    <img src="" alt="Proof Preview" id="proofPreview" class="img-fluid rounded border" style="max-width: 100%; max-height: 300px; object-fit: contain; display: none;">
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary" name="complete_payment">Complete Payment</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-xl-6">
                    <div class="card card-h-100">
                        <!-- TradingView Widget BEGIN -->
                        <div class="tradingview-widget-container">
                            <div class="tradingview-widget-container__widget"></div>
                            <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-symbol-overview.js" async>
                            {
                                "symbols": [
                                [
                                    "FRED:SP500|1D"
                                ],
                                [
                                    "FRED:NDQ100|1D"
                                ],
                                [
                                    "BLACKBULL:US30|1D"
                                ]
                                ],
                                "chartOnly": false,
                                "width": "100%",
                                "height": "100%",
                                "locale": "en",
                                "colorTheme": "light",
                                "autosize": true,
                                "showVolume": false,
                                "showMA": false,
                                "hideDateRanges": false,
                                "hideMarketStatus": true,
                                "hideSymbolLogo": false,
                                "scalePosition": "right",
                                "scaleMode": "Normal",
                                "fontFamily": "-apple-system, BlinkMacSystemFont, Trebuchet MS, Roboto, Ubuntu, sans-serif",
                                "fontSize": "10",
                                "noTimeScale": false,
                                "valuesTracking": "1",
                                "changeMode": "price-and-percent",
                                "chartType": "area",
                                "lineWidth": 2,
                                "lineType": 0,
                                "dateRanges": [
                                "1d|1",
                                "1m|1D",
                                "3m|60",
                                "12m|1D",
                                "60m|1W",
                                "all|1M"
                                ]
                            }
                            </script>
                        </div>
                        <!-- TradingView Widget END -->
                    </div>
                </div>
            </div><!--End row-->

            <!-- start:: Default Modal -->
            <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog"
            aria-labelledby="modalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel">
                            Wallet Address Copied
                        </h5>
                    </div>
                    <div class="modal-body">
                        <div class="text-center">
                            <p class="fw-bold mb-1">
                                <span style="display: inline-flex; justify-content: center; align-items: center; background-color: #144B4B; border-radius: 50%; width: 100px; height: 100px;">
                                    <i class="ri-check-line text-white" style="font-size: 2.5rem;"></i>
                                </span>

                            </p>
                            <p class="fw-bold mb-1 text-primary fs-5">{{ wallet_address.crypto_address }}</p>
                        </div>

                    </div>
                </div>
            </div>
        </div><!--End modal-->

        </div><!--End container-fluid-->

        <script>
            document.getElementById('paymentProof').addEventListener('change', function(event) {
                const preview = document.getElementById('proofPreview');
                const file = event.target.files[0];

                if (file && file.type.startsWith('image/')) {
                    preview.src = URL.createObjectURL(file);
                    preview.style.display = 'block'; // show only after selection
                } else {
                    preview.src = '';
                    preview.style.display = 'none';
                }

            });
            document.getElementById('copyAddress').addEventListener('click', function() {
                const walletAddress = document.getElementById('walletAddress');
                navigator.clipboard.writeText(walletAddress.value)
            });
        </script>

    </main><!--End app-wrapper-->

{% endblock content %}

templates/backend/crypto/deposit.html
{% extends "base_main.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
  {% include "partials/backend/head.html" %}
{% endblock head %}
{% block title %} Crypto Deposit {% endblock %}
{% block content %}
    {% with title_sub="Crypto Deposit" title="Crypto Deposit"%}
    {% include "partials/backend/pagetitle.html" %}
    {% endwith %}

<!--begin::App-->
            {% include "partials/backend/messages.html" %}
            <div class="row">

                <div class="col-12 col-xl-5">
                    <div class="card card-h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">Crypto Deposit</h5>
                        </div>
                        <div class="card-body">
                            <p class="text-muted mb-4">Choose the crypto you want to deposit, Only send the exact cryptocurrency and amount to the correct address, Our team will verify your payment. Once confirmed, your account will be credited.</p>
                            <form method="POST" action="{% url 'trx:complete_crypto_deposit' %}">
                                {% csrf_token %}
                                {{form|crispy}}
                                <button type="submit" class="btn btn-primary" name="crypto_deposit">Proceed with Payment</button>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-xl-7">
                    <div class="card overflow-hidden card-h-100 p-4">
                        <!-- TradingView Widget BEGIN -->
                        <div class="tradingview-widget-container" style="height:100%;width:100%">
                            <div class="tradingview-widget-container__widget" style="height:calc(100% - 32px);width:100%"></div>
                            <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js" async>
                                {
                                    "autosize": true,
                                    "symbol": "NASDAQ:AAPL",
                                    "interval": "D",
                                    "timezone": "exchange",
                                    "theme": "light",
                                    "backgroundColor": "rgba(255, 255, 255, 1)",
                                    "style": "3",
                                    "hide_top_toolbar": true,
                                    "save_image": false,
                                    "locale": "en",
                                    "calendar": false,
                                    "support_host": "https://www.tradingview.com"
                                }
                            </script>
                        </div>
                        <!-- TradingView Widget END -->
                    </div>
                    </div>
                </div>

                <div class="col-12 col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Recent Transactions</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-box table-responsive">
                                <table class="table table-hover text-nowrap">
                                    <thead class="table-light border-0">
                                        <tr>
                                            <th>SN</th>
                                            <th>Transaction Ref</th>
                                            <th>Amount</th>
                                            <th>Network</th>
                                            <th>Status</th>
                                            <th>Receiving Wallet</th>
                                            <th>Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if object_list %}
                                            {% for object in object_list %}
                                            <tr>
                                                <td>{{forloop.counter}}</td>
                                                <td>{{object.transaction.trx_reference|upper}}</td>
                                                <td>${{object.amount}}</td>
                                                <td>{{object.crypto_type}}</td>
                                                <td>
                                                    {% if object.is_confirmed %}
                                                        <span class="badge bg-success-subtle text-success py-1 rounded-3 border border-success">Completed</span>
                                                        {% else %}
                                                        <span class="badge bg-warning-subtle text-warning py-1 rounded-3 border border-warning">Pending</span>

                                                    {% endif %}
                                                </td>
                                                <td>{{object.crypto_type.crypto_address}}</td>
                                                <td>{{object.timestamp}}</td>
                                            </tr>
                                            {% endfor %}
                                        {% else %}
                                            {% include 'partials/backend/empty_list.html' %}
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div><!--End row-->
        </div><!--End container-fluid-->
    </main><!--End app-wrapper-->
{% endblock content %}