arc_trustpay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

APP_NAME = settings.APP_NAME

urlpatterns = [
    path('', include('trustpay_landing.urls', namespace='landing')),
    path('', include('trustpay_auth.urls', namespace='auth')),
    path(f"{APP_NAME}-admin/", admin.site.urls),
    path('auth/', include('trustpay_user.urls', namespace='user')),
    path('auth/', include('trustpay_trx.urls', namespace='trx')),
    path('auth/', include('trustpay_admin.urls', namespace='adm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = f"{APP_NAME}"
admin.site.site_title = f"{APP_NAME}"
admin.site.index_title = f"Welcome to {APP_NAME}"

trustpay_admin/urls.py
# My Django imports
from django.urls import path, include

app_name = 'adm'

# My App imports
from trustpay_admin.views import *

# URL patterns for the trustpay_landing app
urlpatterns = [
    path('manage_cheque_deposit', ManageChequeDepositView.as_view(), name="manage_cheque_deposit"),
    path('manage_crypto_deposit', ManageCryptoDepositView.as_view(), name="manage_crypto_deposit"),
    path('manage_credit_debit', CreditDebitTransactionView.as_view(), name="manage_credit_debit"),
    path('manage_loan', ManageLoanView.as_view(), name="manage_loan"),
    path('manage_users', ManageUsersView.as_view(), name="manage_users"),
]

trustpay_auth/urls.py
# My Django imports
from django.urls import path, include

app_name = 'auth'

# My App imports
from trustpay_auth.views import *

# URL patterns for the trustpay_landing app
urlpatterns = [
    path('login', LoginPageView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('register', RegisterPageView.as_view(), name="register"),
    path('forget-password', ForgotPasswordPageView.as_view(), name="forget-password"),
    path('reset-password//<uidb64>/<token>', ResetPasswordPageView.as_view(), name="reset-password"),
    path('signout', SignOutPageView.as_view(), name="signout"),
    path('welcome', EmailPreviewPageView.as_view(), name="welcome"),
]

trustpay_trx/urls.py
# My Django imports
from django.urls import path, include

app_name = 'trx'

# My App imports
from trustpay_trx.views import *

# URL patterns for the trustpay_users app
urlpatterns = [
    path('crypto_deposit', CryptoDepositView.as_view(), name="crypto_deposit"),
    path('complete_crypto_deposit', CompleteCryptoDepositView.as_view(), name="complete_crypto_deposit"),

    path('cheque_deposit', ChequeDepositView.as_view(), name="cheque_deposit"),

    path('internal_transfer', InternalTransferView.as_view(), name="internal_transfer"),
    path('validate_recipient_account/', validate_recipient_account, name="validate_recipient_account"),
    path('confirm_internal_transfer', ConfirmInternalTransferView.as_view(), name="confirm_internal_transfer"),

    path('ach_transfer', ACHTransferView.as_view(), name="ach_transfer"),
    path('confirm_ach_transfer', ConfirmACHTransferView.as_view(), name="confirm_ach_transfer"),

    path('d_wire_transfer', DomesticWireView.as_view(), name="d_wire_transfer"),
    path('confirm_d_wire_transfer', ConfirmDomesticWireView.as_view(), name="confirm_d_wire_transfer"),

    path('f_wire_transfer', InternationalWireView.as_view(), name="f_wire_transfer"),
    path('confirm_f_wire_transfer', ConfirmInternationalWireView.as_view(), name="confirm_f_wire_transfer"),

    path('credit_debit_transaction', CreditDebitTransactionView.as_view(), name="credit_debit_transaction"),

    path('take_loan', TakeLoanView.as_view(), name="take_loan"),
    path('repay_loan', RepayLoanView.as_view(), name="repay_loan"),

    path('transactions', TransactionPageView.as_view(), name="transactions"),
]

trustpay_user/urls.py
# My Django imports
from django.urls import path, include

app_name = 'user'

# My App imports
from trustpay_user.views import *

# URL patterns for the trustpay_users app
urlpatterns = [
    path('dashboard', DashboardPageView.as_view(), name="dashboard"),
    path('account_details', UserAccountPageView.as_view(), name="account_details"),
    path('account_manager', AccountManagerView.as_view(), name="account_manager"),
]

templates/partials/backend/auth-background.html
<div class="position-fixed top-0 bottom-0 end-0 start-0 z-0 bg-pattern"></div>
<div class="auth-pattern-shapes d-none d-lg-block"></div>
<div class="auth-pattern-outline d-none d-lg-block"></div>
<div class="auth-pattern-shape extra d-none d-lg-block"></div>
<div class="auth-pattern-extra d-none d-lg-block"></div>

templates/partials/backend/auth-header.html
{% comment %} <header class="px-3 px-md-8 py-5 position-absolute top-0 d-flex justify-content-between align-items-center w-100 z-1">
  <a href="{% url "landing:home" %}" class="d-flex align-items-end logo-main">
    <img height="35" class="logo-dark" alt="Dark Logo" src="/static/frontend/images/logo-big.svg">
    <h3 class="text-body-emphasis fw-bolder mb-0 ms-1"></h3>
  </a>
  <ul class="list-inline mb-0">
    <li class="list-inline-item pe-4 border-end"><a href="{% url "landing:home" %}" class="link-body-emphasis">Home</a></li>
    <li class="list-inline-item pe-4 border-end"><a href="{% url "landing:about" %}" class="link-body-emphasis">About</a></li>
    <li class="list-inline-item pe-4 border-end"><a href="{% url "landing:services" %}" class="link-body-emphasis">Services</a></li>
    <li class="list-inline-item"><a href="{% url "landing:contact" %}" class="link-body-emphasis">Contact</a></li>
    <li class="list-inline-item"><div class="nav-link float-right" id="google_translate_element"></div></li>
  </ul>
</header> {% endcomment %}

templates/partials/backend/auth_nav.html
<!-- Begin Header -->
<header class="app-header" id="appHeader">
    <div class="container-fluid w-100">
        <div class="d-flex justify-content-between align-items-center">
            <div class="d-inline-flex align-items-center gap-2">
                <a href="index.html" class="align-items-end logo-main d-none me-5">
                    <img height="35" width="34" class="logo-dark" alt="Dark Logo" src="/static/frontend/images/logo-big.svg">
                    <h3 class="text-body-emphasis fw-bolder mb-0 ms-1"></h3>
                </a>
                <button type="button" class="vertical-toggle btn header-btn" id="toggleSidebar" aria-label="Toggle Sidebar">
                    <i class="bi bi-arrow-bar-left header-icon"></i>
                </button>
                <button type="button" class="horizontal-toggle btn header-btn d-none" id="toggleHorizontal" aria-label="Toggle Menu">
                    <i class="ri-menu-2-line header-icon"></i>
                </button>
                <!-- Search Bar -->
                <div class="form-icon right d-none d-md-block" data-bs-toggle="modal" data-bs-target="#searchModal">
                    <input type="text" class="form-control form-control-icon bg-transparent rounded-pill min-w-300px" id="Search" placeholder="Search" required>
                    <div class="search-btn">
                        <div><i class="ri-search-line text-muted fs-16"></i></div>
                        <div><span class="badge bg-light-subtle text-muted">CTRL D</span></div>
                    </div>
                </div>
            </div>
            <div class="flex-shrink-0 d-flex align-items-center gap-4">
                <div class="d-flex gap-2 align-items-center">
                    <div class="dropdown pe-dropdown-mega d-none d-md-block">
                        <button class="btn header-btn" type="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Notifications">
                            <i class="bi bi-bell"></i>
                            <div class="icon-dot"></div>
                        </button>
                        <div class="dropdown-menu dropdown-mega-md header-dropdown-menu pe-noti-dropdown-menu p-0">
                            <div class="p-3 border-bottom">
                                <h6 class="d-flex align-items-center mb-0">Notification <span class="badge bg-success-subtle text-success ms-auto">0 Unread</span></h6>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown pe-dropdown-mega d-none d-md-block">
                        <div id="google_translate_element"></div>
                    </div>

                </div>
                <div class="dark-mode-btn" id="toggleMode">
                    <button class="btn header-btn active" id="lightModeBtn" type="button" aria-label="Switch to light mode">
                        <i class="bi bi-brightness-high"></i>
                    </button>
                    <button class="btn header-btn" id="darkModeBtn" type="button" aria-label="Switch to Dark mode">
                        <i class="bi bi-moon-stars"></i>
                    </button>
                </div>
                <div class="dropdown pe-dropdown-mega d-none d-md-block">
                    <button class="header-profile-btn btn gap-1 text-start" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="d-none d-xl-block pe-2">
                            <span class="d-block mb-0 fs-12 fw-semibold">{{request.user.personal_info}}</span>
                            <span class="d-block mb-0 fs-10 text-muted">{{request.user.email}}</span>
                        </div>
                        <span class="header-btn btn position-relative">
                            <img src="{{request.user.pic.url}}" alt="Avatar Image" class="img-fluid rounded-circle">
                        </span>
                    </button>
                    <div class="dropdown-menu dropdown-mega-sm header-dropdown-menu p-3">
                        <div class="border-bottom pb-2 mb-2 d-flex align-items-center gap-2">
                            <img src="{{request.user.pic.url}}" alt="Avatar Image" class="avatar-md">
                            <div>
                                <a href="javascript:void(0)">
                                    <h6 class="mb-0 lh-base">{{request.user.personal_info}}</h6>
                                </a>
                                <p class="mb-0 fs-13 text-muted">{{request.user.email}}</p>
                            </div>
                        </div>
                        <ul class="list-unstyled mb-1 border-bottom pb-1">
                            <li><a class="dropdown-item" href="{% url "user:account_details" %}"><i class="bi bi-person me-2"></i> View Profile</a></li>
                            <li><a class="dropdown-item" href="{% url "user:account_manager" %}"><i class="bi bi-gear me-2"></i> Account Manager</a></li>
                        </ul>

                        <ul class="list-unstyled mb-0">
                            <li><a class="dropdown-item" style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#logoutModal"><i class="bi bi-box-arrow-right me-2"></i> Sign Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- END Header -->
{% include 'partials/backend/modal_logout.html' %}

<!-- Search Modal -->
<div class="modal fade search-modal" id="searchModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header d-block">
          <div class="form-icon">
            <input type="text" class="form-control form-control-icon" id="searchInputInModal" placeholder="Search" required>
            <div class="search-btn w-44px">
              <i class="ri-search-line text-muted fs-16"></i>
            </div>
            <button type="button" class="btn-close position-absolute end-0 top-50 translate-middle-y d-inline-block m-0" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
        </div>
        <div class="modal-body" data-simplebar id="list-items">
          <ul class="list-unstyled mb-0" id="searchList"></ul>
        </div>
      </div>
    </div>
  </div>

templates/partials/backend/auth_scripts.html
{% load static %}
<script src="/static/backend/assets/libs/swiper/swiper-bundle.min.js"></script>
<script src="/static/backend/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/backend/assets/libs/simplebar/simplebar.js"></script>
<script src="/static/backend/assets/js/scroll-top.init.js"></script>
<script src="/static/backend/assets/libs/gridjs/gridjs.umd.js" type="text/javascript"></script>
<script src="/static/backend/assets/libs/apexcharts/apexcharts.min.js"></script>
<!-- File js -->
<script src="/static/backend/assets/js/dashboard/e-commerce.init.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'frontend/js/loader.js' %}"></script>
<script>
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });

        $("#remove").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 10000);
</script>
<!-- App js -->
<script type="module" src="/static/backend/assets/js/app.js"></script>
<script type="text/javascript">
    function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<script src="/static/backend/assets/js/auth/auth.init.js"></script>
<script type="module" src="/static/backend/assets/js/ui/modal.init.js"></script>

templates/partials/backend/empty_list.html
<tr>
    <td colspan="15">
        <div class="jumbotron text-center p-4">
            <!-- illustration can be used here too -->
            <p style="font-size: 5em;">📂</p> <br>
            <p style="font-size: 1.5em; margin-top: -60px;">No Record Here!</p>
        </div>
    </td>
</tr>

templates/partials/backend/footer.html
<!-- Begin Footer -->
<footer class="footer">
    <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center gap-2">
            <script>document.write(new Date().getFullYear())</script> © {{app_name}}.
            <div class="text-sm-end d-none d-sm-block">
                All rights reserved.
            </div>
        </div>
    </div>
</footer>
<!-- END Footer -->

templates/partials/backend/head.html
{% load static %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<meta content="{{app_name}} - Financial service" name="description" />
<meta content="{{app_name}}" name="author" />

<!-- layout setup -->
<script type="module" src="/static/backend/assets/js/layout-setup.js"></script>

<!-- App favicon -->
<link rel="shortcut icon" href="/static/frontend/images/logo-small.svg">
<link rel="stylesheet" href="/static/backend/assets/libs/gridjs/theme/mermaid.min.css">
<!-- Simplebar Css -->
<link rel="stylesheet" href="/static/backend/assets/libs/simplebar/simplebar.min.css">
<!-- Swiper Css -->
<link href="/static/backend/assets/libs/swiper/swiper-bundle.min.css" rel="stylesheet">
<!-- Nouislider Css -->
<link href="/static/backend/assets/libs/nouislider/nouislider.min.css" rel="stylesheet">
<!-- Bootstrap Css -->
<link href="/static/backend/assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css">

<!--icons css-->
<link href="/static/backend/assets/css/icons.min.css" rel="stylesheet" type="text/css">
<!-- App Css-->
<link href="/static/backend/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css">
<link href="/static/backend/assets/css/check.css" id="app-style" rel="stylesheet" type="text/css">
<link href="{% static 'frontend/css/loader.css' %}" rel="stylesheet">
<style>
    .asteriskField {
        color: red;
        padding-left: 4px;
    }
</style>
<script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.5/dist/htmx.min.js" integrity="sha384-t4DxZSyQK+0Uv4jzy5B0QyHyWQD2GFURUmxKMBVww9+e2EJ0ei/vCvv7+79z0fkr" crossorigin="anonymous"></script>

<script src="//code.jivosite.com/widget/BD6jmIjGkn" async></script>

templates/partials/backend/messages.html
{% if messages  %}
	<div class="messages mt-4">
		{% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %} role="alert">
      {{ message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
		{% endfor %}
	</div>
{% endif %}

templates/partials/backend/modal_logout.html
<div class="modal fade" id="logoutModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ready to Leave?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"><span>×</span>
                </button>
            </div>
            <div class="modal-body">Select "Log Out" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
                <form action="{% url 'auth:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning btn-block">Log out</button>
                </form>
            </div>
        </div>
    </div>
</div>  

templates/partials/backend/pagetitle.html
<div class="main-breadcrumb d-flex align-items-center my-3 position-relative">
    <h2 class="breadcrumb-title mb-0 flex-grow-1 fs-14">{{ title }}</h2>
    <div class="flex-shrink-0">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-end mb-0">
                <li class="breadcrumb-item"><a href="{{ url }}">{{ title_sub }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
            </ol>
        </nav>
    </div>
</div>

templates/partials/backend/scripts.html
<!-- JAVASCRIPT -->
{% load static %}
<script src="/static/backend/assets/libs/swiper/swiper-bundle.min.js"></script>
<script src="/static/backend/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/backend/assets/libs/simplebar/simplebar.js"></script>
<script src="/static/backend/assets/js/scroll-top.init.js"></script>
<script src="/static/backend/assets/js/auth/auth.init.js"></script>
<script type="module" src="/static/backend/assets/js/ui/modal.init.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'frontend/js/loader.js' %}"></script>

<script>
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });

        $("#remove").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 10000);
</script>
<script type="text/javascript">
    function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL}, 'google_translate_element');
    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

templates/partials/backend/scroll-to-top.html
<!-- Begin scroll top -->
<div class="progress-wrap d-flex align-items-center justify-content-center cursor-pointer h-40px w-40px position-fixed" id="progress-scroll" style="bottom: 80px !important;">
  <svg class="progress-circle w-100 h-100 position-absolute" viewBox="0 0 100 100">
    <circle cx="50" cy="50" r="45" class="progress" />
  </svg>
  <i class="ri-arrow-up-line fs-16 z-1 position-relative text-primary"></i>
</div>
<!-- END scroll top -->

templates/partials/backend/sidebar.html
<aside class="pe-app-sidebar" id="sidebar">
    <div class="pe-app-sidebar-logo px-6 d-flex align-items-center position-relative">
        <!--begin::Brand Image-->
        <a href="{% url "landing:home" %}" class="d-flex align-items-end logo-main">
            <img  class="logo-dark" alt="Dark Logo" src="/static/frontend/images/logo-small.svg">
            <img height="35" width="34" class="logo-light" alt="Light Logo" src="/static/frontend/images/logo-small.svg">
            <h5 class="text-body-emphasis fw-bolder mb-0 ms-1" style="color: #144B4B !important;">
                {{ app_name }}
            </h5>
        </a>
        <button type="button" id="sidebarDefaultArrow" class="btn btn-sm p-0 fs-16 text-body-emphasis ms-auto float-end d-none icon-hover-btn d-none"><i class="ri-arrow-right-line fs-5"></i></button>
        <!--end::Brand Image-->
    </div>
    <nav class="pe-app-sidebar-menu nav nav-pills" data-simplebar id="sidebar-simplebar">
        <div class="d-flex align-items-start flex-column w-100">
            <ul class="pe-main-menu list-unstyled">
                <!-- Main Menu -->
                <li class="pe-menu-title">Main</li>
                <li class="pe-slide pe-has-sub">
                    <a href="{% url "user:dashboard" %}" class="pe-nav-link">
                        <i class="ri-dashboard-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Dashboards</span>
                    </a>
                </li>

                <!-- Pages -->
                <li class="pe-menu-title">Banking</li>
                <li class="pe-slide pe-has-sub">
                    <a href="#collapseAuth" class="pe-nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseAuth">
                        <i class="ri-wallet-3-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Deposit</span>
                        <i class="ri-arrow-down-s-line pe-nav-arrow"></i>
                    </a>
                    <ul class="pe-slide-menu collapse" id="collapseAuth">
                        <li class="slide pe-nav-content1">
                            <a href="javascript:void(0)">Deposit</a>
                        </li>
                        {% if request.user.is_staff %}
                        <li class="pe-slide-item">
                            <a href="{% url "adm:manage_cheque_deposit" %}" class="pe-nav-link">
                               Manage Cheque
                            </a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "adm:manage_crypto_deposit" %}" class="pe-nav-link">
                               Manage Crypto
                            </a>
                        </li>

                        {% else %}
                        <li class="pe-slide-item">
                            <a href="{% url "trx:cheque_deposit" %}" class="pe-nav-link">
                               Cheque Deposit
                            </a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:crypto_deposit" %}" class="pe-nav-link">
                               Crypto Deposit
                            </a>
                        </li>

                        {% endif %}
                    </ul>
                </li>
                {% if request.user.is_staff %}

                <!-- Pages -->
                <li class="pe-menu-title">Users</li>
                <li class="pe-slide pe-has-sub">
                    <a href="#collapseUsers" class="pe-nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseUsers">
                        <i class="ri-user-3-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Users</span>
                        <i class="ri-arrow-down-s-line pe-nav-arrow"></i>
                    </a>
                    <ul class="pe-slide-menu collapse" id="collapseUsers">
                        <li class="slide pe-nav-content1">
                            <a href="javascript:void(0)">Users</a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "adm:manage_users" %}" class="pe-nav-link">
                               Manage Users
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}

                {% if not request.user.is_staff %}
                <li class="pe-slide pe-has-sub">
                    <a href="#collapsePages" class="pe-nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapsePages">
                        <i class="ri-exchange-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Transfer</span>
                        <i class="ri-arrow-down-s-line pe-nav-arrow"></i>
                    </a>
                    <ul class="pe-slide-menu collapse" id="collapsePages">
                        <li class="slide pe-nav-content1">
                            <a href="javascript:void(0)">Transfer</a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:internal_transfer" %}" class="pe-nav-link">
                                Internal Transfer
                            </a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:ach_transfer" %}" class="pe-nav-link">
                                ACH Transfer
                            </a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:d_wire_transfer" %}" class="pe-nav-link">
                                Domestic Wire
                            </a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:f_wire_transfer" %}" class="pe-nav-link">
                                International Wire
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}

                <!-- Components -->
                <li class="pe-menu-title">Transactions</li>
                <li class="pe-slide pe-has-sub">
                    <a href="#collapseBaseUI" class="pe-nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseBaseUI">
                        <i class="ri-pencil-ruler-2-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Transactions</span>
                        <i class="ri-arrow-down-s-line pe-nav-arrow"></i>
                    </a>
                    <ul class="pe-slide-menu collapse" id="collapseBaseUI">
                        <li class="slide pe-nav-content1">
                            <a href="javascript:void(0)">Transactions</a>
                        </li>
                        {% if request.user.is_staff %}
                        <li class="pe-slide-item">
                            <a href="{% url "adm:manage_credit_debit" %}" class="pe-nav-link">Manage Credit / Debit</a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "adm:manage_loan" %}" class="pe-nav-link">Loan Transactions</a>
                        </li>
                        {% else %}
                        <li class="pe-slide-item">
                            <a href="{% url "trx:credit_debit_transaction" %}" class="pe-nav-link">Credit / Debit</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                {% if not request.user.is_staff %}
                <li class="pe-slide pe-has-sub">
                    <a href="#collapseAdvancedUI" class="pe-nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseAdvancedUI">
                        <i class="ri-hand-coin-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Loans</span>
                        <i class="ri-arrow-down-s-line pe-nav-arrow"></i>
                    </a>
                    <ul class="pe-slide-menu collapse" id="collapseAdvancedUI">
                        <li class="slide pe-nav-content1">
                            <a href="javascript:void(0)">Loans</a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:take_loan" %}" class="pe-nav-link">Take Loans</a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "trx:repay_loan" %}" class="pe-nav-link">Repay Loans</a>
                        </li>
                    </ul>
                </li>
                {% endif %}

                <!-- Icons & Maps -->
                <li class="pe-menu-title">Settings</li>
                <li class="pe-slide pe-has-sub">
                    <a href="#collapseIcons" class="pe-nav-link" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseIcons">
                        <i class="ri-compasses-2-line pe-nav-icon"></i>
                        <span class="pe-nav-content">Settings</span>
                        <i class="ri-arrow-down-s-line pe-nav-arrow"></i>
                    </a>
                    <ul class="pe-slide-menu collapse" id="collapseIcons">
                        <li class="slide pe-nav-content1">
                            <a href="javascript:void(0)">Settings</a>
                        </li>
                        <li class="pe-slide-item">
                            <a href="{% url "user:account_details" %}" class="pe-nav-link">
                                Account Details
                            </a>
                        </li>
                        {% if not request.user.is_staff %}

                        <li class="pe-slide-item">
                            <a href="{% url "user:account_manager" %}" class="pe-nav-link">
                                Account Manager
                            </a>
                        </li>
                        {% endif %}
                        <li class="pe-slide-item">
                            <a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#logoutModal" class="pe-nav-link">
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Widgets -->

        </div>
    </nav>
</aside>