arc_trustpay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

APP_NAME = settings.APP_NAME

urlpatterns = [
    path('', include('trustpay_landing.urls', namespace='landing')),
    path('', include('trustpay_auth.urls', namespace='auth')),
    path(f"{APP_NAME}-admin/", admin.site.urls),
    path('auth/', include('trustpay_user.urls', namespace='user')),
    path('auth/', include('trustpay_trx.urls', namespace='trx')),
    path('auth/', include('trustpay_admin.urls', namespace='adm')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = f"{APP_NAME}"
admin.site.site_title = f"{APP_NAME}"
admin.site.index_title = f"Welcome to {APP_NAME}"

trustpay_auth/urls.py
# My Django imports
from django.urls import path, include

app_name = 'auth'

# My App imports
from trustpay_auth.views import *

# URL patterns for the trustpay_landing app
urlpatterns = [
    path('login', LoginPageView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('register', RegisterPageView.as_view(), name="register"),
    path('forget-password', ForgotPasswordPageView.as_view(), name="forget-password"),
    path('reset-password//<uidb64>/<token>', ResetPasswordPageView.as_view(), name="reset-password"),
    path('signout', SignOutPageView.as_view(), name="signout"),
    path('welcome', EmailPreviewPageView.as_view(), name="welcome"),
]

trustpay_landing/urls.py
# My Django imports
from django.urls import path, include

app_name = 'landing'

# My App imports
from trustpay_landing.views import *

# URL patterns for the trustpay_landing app
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('contact', ContactUsView.as_view(), name="contact"),
    path('about', AboutUsView.as_view(), name="about"),
    path('services', ServicesView.as_view(), name="services"),
]

templates/partials/frontend/faq.html
{% load static %}
<section class="section faq__v2" id="faq">
    <div class="container">
        <div class="row mb-4">
        <div class="col-md-6 col-lg-7 mx-auto text-center"><span class="subtitle text-uppercase mb-3" data-aos="fade-up" data-aos-delay="0">FAQ</span>
            <h2 class="h2 fw-bold mb-3" data-aos="fade-up" data-aos-delay="0">Frequently Asked Questions</h2>
            <p data-aos="fade-up" data-aos-delay="100">Utilize our tools to develop your concepts and bring your vision to life. Once complete, effortlessly share your creations.</p>
        </div>
        </div>
        <div class="row">
        <div class="col-md-8 mx-auto" data-aos="fade-up" data-aos-delay="200">
            <div class="faq-content">
            <div class="accordion custom-accordion" id="accordionPanelsStayOpenExample">
                <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne"> How do I open a new account on {{app_name}}? </button>
                </h2>
                <div class="accordion-collapse collapse show" id="panelsStayOpen-collapseOne">
                    <div class="accordion-body"> To open a new account, click on the “Sign Up” button on our homepage and follow the step-by-step registration process. Youll need to provide some personal details.</div>
                </div>
                </div>
                <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo"> How secure is my online banking information? </button>
                </h2>
                <div class="accordion-collapse collapse" id="panelsStayOpen-collapseTwo">
                    <div class="accordion-body">Your data is protected with advanced encryption, and continuous security monitoring to ensure your information stays safe at all times.</div>
                </div>
                </div>
                <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree"> Can I transfer funds internationally? </button>
                </h2>
                <div class="accordion-collapse collapse" id="panelsStayOpen-collapseThree">
                    <div class="accordion-body">Yes. {{app_name}} allows international money transfers. Make sure to input the correct SWIFT/BIC code and the recipient's banking details.</div>
                </div>
                </div>
                <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">  How do I apply for a mortgage?</button>
                </h2>
                <div class="accordion-collapse collapse" id="panelsStayOpen-collapseFour">
                    <div class="accordion-body">Log into your account, go to the Mortgage section, and complete the application form. You'll need to provide financial documents like credit reports and proof of income.</div>
                </div>
                </div>
                <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive"> What should I do if I forget my login details? </button>
                </h2>
                <div class="accordion-collapse collapse" id="panelsStayOpen-collapseFive">
                    <div class="accordion-body">Click the “Forgot Password?” link on the login page to reset your password via email verification.</div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <!-- End FAQ-->
</section>

templates/partials/frontend/footer.html
{% load static %}
<footer class="footer pt-5 pb-5">
    <div class="container">
      <div class="row justify-content-between mb-5 g-xl-5">
        <div class="col-md-4 mb-5 mb-lg-0">
          <h3 class="mb-3">About</h3>
          <p class="mb-4">we are redefining online banking by offering secure, flexible, and innovative financial solutions tailored to individual and business needs.</p>
        </div>
        <div class="col-md-7">
          <div class="row g-2">
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
              <h3 class="mb-3">Company</h3>
              <ul class="list-unstyled">
                <li><a href="">Terms &amp; Conditions</a></li>
                <li><a href="">Privacy Policy</a></li>
              </ul>
            </div>
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
              <h3 class="mb-3">Accounts</h3>
              <ul class="list-unstyled">
                <li><a href="{% url "auth:register" %}">Register</a></li>
                <li><a href="{% url "auth:login" %}">Sign in</a></li>
              </ul>
            </div>
            <div class="col-md-6 col-lg-4 mb-4 mb-lg-0 quick-contact">
              <h3 class="mb-3">Contact</h3>
              <a class="d-flex mb-3" href="mailto:{{company_email}}"><i class="bi bi-envelope-fill me-3"></i><span>{{company_email}}</span></a><a class="d-flex mb-3" href="tel://{{company_phone}}"><i class="bi bi-telephone-fill me-3"></i><span>{{company_phone}}</span></a>
            </div>
          </div>
        </div>
      </div>
      <div class="row credits pt-3">
        <div class="col-xl-8 text-center text-xl-start mb-3 mb-xl-0">
          &copy;
          <script>document.write(new Date().getFullYear());</script> {{app_name}}.
            All rights reserved.
        </div>
      </div>
    </div>
  </footer>

templates/partials/frontend/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- ======= Google Font =======-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&amp;display=swap" rel="stylesheet">
<!-- End Google Font-->
<link rel="shortcut icon" href="/static/frontend/images/logo-small.svg">

<!-- ======= Styles =======-->
<link href="{% static 'frontend/vendors/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'frontend/vendors/bootstrap-icons/font/bootstrap-icons.min.css' %}" rel="stylesheet">
<link href="{% static 'frontend/vendors/glightbox/glightbox.min.css' %}" rel="stylesheet">
<link href="{% static 'frontend/vendors/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
<link href="{% static 'frontend/vendors/aos/aos.css' %}" rel="stylesheet">
<!-- End Styles-->

<!-- ======= Theme Style =======-->
<link href="{% static 'frontend/css/loader.css' %}" rel="stylesheet">
<link href="{% static 'frontend/css/style.css' %}" rel="stylesheet">
<!-- End Theme Style-->
<script src="//code.jivosite.com/widget/BD6jmIjGkn" async></script>

templates/partials/frontend/how_it_works.html
{% load static %}
<section class="section howitworks__v1" id="how-it-works">
    <div class="container">
        <div class="row mb-5">
        <div class="col-md-6 text-center mx-auto"><span class="subtitle text-uppercase mb-3" data-aos="fade-up" data-aos-delay="0">How it works</span>
            <h2 data-aos="fade-up" data-aos-delay="100">How It Works</h2>
            <p data-aos="fade-up" data-aos-delay="200">Our platform is designed to make managing your finances simple and efficient. Follow these easy steps to get started: </p>
        </div>
        </div>
        <div class="row g-md-5">
        <div class="col-md-6 col-lg-3">
            <div class="step-card text-center h-100 d-flex flex-column justify-content-start position-relative" data-aos="fade-up" data-aos-delay="0">
            <div data-aos="fade-right" data-aos-delay="500"><img class="arch-line" src="{% static 'frontend/images/arch-line.svg' %}" alt="Arc-trustPay image placeholder"></div><span class="step-number rounded-circle text-center fw-bold mb-5 mx-auto">1</span>
            <div>
                <h3 class="fs-5 mb-4">Sign Up</h3>
                <p>Create a secure account using your email or phone number in just a few minutes.</p>
            </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="600">
            <div class="step-card reverse text-center h-100 d-flex flex-column justify-content-start position-relative">
            <div data-aos="fade-right" data-aos-delay="1100"><img class="arch-line reverse" src="{% static 'frontend/images/arch-line-reverse.svg' %}" alt="Arc-trustPay image placeholder"></div><span class="step-number rounded-circle text-center fw-bold mb-5 mx-auto">2</span>
            <h3 class="fs-5 mb-4">Set Up Your Profile</h3>
            <p>Add your personal and financial details to help us tailor your experience.</p>
            </div>
        </div>
        <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="1200">
            <div class="step-card text-center h-100 d-flex flex-column justify-content-start position-relative">
            <div data-aos="fade-right" data-aos-delay="1700"><img class="arch-line" src="{% static 'frontend/images/arch-line.svg' %}" alt="Arc-trustPay image placeholder"></div><span class="step-number rounded-circle text-center fw-bold mb-5 mx-auto">3</span>
            <h3 class="fs-5 mb-4">Explore Features</h3>
            <p>Access a range of services including transfers, deposits, loans, and more—all from your dashboard.</p>
            </div>
        </div>
        <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="1800">
            <div class="step-card last text-center h-100 d-flex flex-column justify-content-start position-relative"><span class="step-number rounded-circle text-center fw-bold mb-5 mx-auto">4</span>
            <div>
                <h3 class="fs-5 mb-4">Start Banking</h3>
                <p>Begin using our powerful banking tools for everyday financial needs, with 24/7 access and support.</p>
            </div>
            </div>
        </div>
        </div>
    </div>
</section>

templates/partials/frontend/nav.html
{% load static %}
<header class="fbs__net-navbar navbar navbar-expand-lg dark" aria-label="{{app_name}} navbar">
    <div class="container d-flex align-items-center justify-content-between">


      <!-- Start Logo-->
      <a class="navbar-brand w-auto" href="index.html">
        <!-- If you use a text logo, uncomment this if it is commented-->
        <!-- Vertex-->

        <!-- If you plan to use an image logo, uncomment this if it is commented-->

        <!-- logo dark--><img class="logo dark img-fluid" src="{% static 'frontend/images/logo-big.svg' %}" alt="{{app_name}} image placeholder">

        <!-- logo light--><img class="logo light img-fluid" src="{% static 'frontend/images/logo-big.svg' %}" alt="{{app_name}} image placeholder">

        </a>
      <!-- End Logo-->

      <!-- Start offcanvas-->
      <div class="offcanvas offcanvas-start w-75" id="fbs__net-navbars" tabindex="-1" aria-labelledby="fbs__net-navbarsLabel">


        <div class="offcanvas-header">
          <div class="offcanvas-header-logo">
            <!-- If you use a text logo, uncomment this if it is commented-->

            <!-- h5#fbs__net-navbarsLabel.offcanvas-title Vertex-->

            <!-- If you plan to use an image logo, uncomment this if it is commented-->
            <a class="logo-link" id="fbs__net-navbarsLabel" href="index.html">


              <!-- logo dark--><img class="logo dark img-fluid" src="{% static 'frontend/images/logo-big.svg' %}" alt="{{app_name}} image placeholder">

              <!-- logo light--><img class="logo light img-fluid" src="{% static 'frontend/images/logo-big.svg' %}" alt="{{app_name}} image placeholder"></a>

          </div>
          <button class="btn-close btn-close-black" type="button" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body align-items-lg-center">
          <ul class="navbar-nav nav me-auto ps-lg-5 mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link scroll-link {% if request.path == '/'%}active{% endif %}" aria-current="page" href="{% url "landing:home" %}">Home</a></li>
            <li class="nav-item"><a class="nav-link scroll-link {% if request.path == '/about'%}active{% endif %}" href="{% url "landing:about" %}">About</a></li>
            <li class="nav-item"><a class="nav-link scroll-link {% if request.path == '/services'%}active{% endif %}" href="{% url "landing:services" %}">Services</a></li>
            <li class="nav-item"><a class="nav-link scroll-link {% if request.path == '/contact'%}active{% endif %}" href="{% url "landing:contact" %}">Contact</a></li>
            <li class="nav-item"><div class="nav-link float-right" id="google_translate_element"></div></li>

          </ul>
        </div>
      </div>
      <!-- End offcanvas-->

      <div class="ms-auto w-auto">


        <div class="header-social d-flex align-items-center gap-1"><a class="btn btn-primary py-2" href="{% url "auth:login" %}">Get Started</a>

          <button class="fbs__net-navbar-toggler justify-content-center align-items-center ms-auto" data-bs-toggle="offcanvas" data-bs-target="#fbs__net-navbars" aria-controls="fbs__net-navbars" aria-label="Toggle navigation" aria-expanded="false">
            <svg class="fbs__net-icon-menu" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <line x1="21" x2="3" y1="6" y2="6"></line>
              <line x1="15" x2="3" y1="12" y2="12"></line>
              <line x1="17" x2="3" y1="18" y2="18"></line>
            </svg>
            <svg class="fbs__net-icon-close" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M18 6 6 18"></path>
              <path d="m6 6 12 12"></path>
            </svg>
          </button>

        </div>

      </div>
    </div>
</header>

templates/partials/frontend/preloader.html
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader-5">
    </div>
</div>

templates/partials/frontend/script.html
{% load static %}
<!-- ======= Javascripts =======-->
<script src="{% static 'frontend/vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'frontend/vendors/gsap/gsap.min.js' %}"></script>
<script src="{% static 'frontend/vendors/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'frontend/vendors/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'frontend/vendors/glightbox/glightbox.min.js' %}"></script>
<script src="{% static 'frontend/vendors/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'frontend/vendors/aos/aos.js' %}"></script>
<script src="{% static 'frontend/vendors/purecounter/purecounter.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'frontend/js/loader.js' %}"></script>
<script src="{% static 'frontend/js/custom.js' %}"></script>
<!-- End JavaScripts-->
<script type="text/javascript">
    function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL}, 'google_translate_element');
    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

templates/partials/frontend/scroll-top.html
{% load static %}
<button id="back-to-top"><i class="bi bi-arrow-up-short"></i></button>